-- oxy:deploy-phase=pre
-- Bootstrap migration for Task 1 of the Mongo->Postgres port. The schema is
-- genuinely empty (no tables) at this point in the migration; this file
-- exists only so the drizzle journal has a real, non-empty entry.
--
-- @oxyhq/db/migrate's readJournal() refuses to treat a zero-entries journal
-- as "nothing to do" (an empty read must never be mistaken for a clean run):
-- `drizzle-kit generate` against a genuinely empty schema produces a journal
-- with `"entries":[]`, which this migrator refuses rather than applies. A
-- `--custom` migration is the standard drizzle-kit mechanism for exactly
-- this: a real journal entry that applies no DDL.
SELECT 1;
